### ISSUE TITLE
integration with home assistant

### ISSUE THREAD

**Issue by jan-bogaerts** [Tiemooowh/pyTeletask#1]
Hi, 
I contacted you a while ago about this plugin. I'm finally at a point where I can start installing the home automation. So I have my home-assistant installed and I also installed your package. Should I now be able to use the configuration like this:
teletask:
  host: 192.168.1.100
  port: 55957

light:
  - platform: teletask
    doip_component: relay
    address: 1
    name: Light Kitchen

or are there any more steps to do? Also, besides light, are there any other types supported? I suppose sensor?

**Comment by Tiemooowh** [comment]
Hi Jan,

Your Teletask Micros+ / Picos should be unlocked with the TDS15132 license.
Once this is done you can apply this config.

Available components are:
- light
- switch

Corresponding with the doip_component:
- relay
- switch
- flag
- locmood
- genmood

Br
T

**Comment by jan-bogaerts** [comment]
So, I finally got to this again. Installed the license key. Next, I did the following things to add the module:
- created a directory /homeassistant/.homeassistant/custom_components/teletask
- copied __init__.py, light.py, switch.py into that folder
- I had to change __init__.py (line 34), removed the 'await' (failed otherwise)
- installed the pyTeletask module into the venv of homeassistant
- checked if I can reach the teletask server on port 55957 from the homeassistant device with command nc -zv 192.168.1.2 55957 (which works)
- added the following config:

teletask:
  host: 192.168.1.2
  port: 55957

light:
  - platform: teletask
    doip_component: relay
    address: 1
    name: licht_keuken

but now I keep getting startup errors in homeassistant:
Error during setup of component teletask
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/home/homeassistant/.homeassistant/custom_components/teletask/__init__.py", line 35, in async_setup
    await hass.data[DATA_TELETASK].start()
  File "/home/homeassistant/.homeassistant/custom_components/teletask/__init__.py", line 68, in start
    port=self.config[DOMAIN][CONF_PORT])
  File "/srv/homeassistant/lib/python3.7/site-packages/teletask/teletask.py", line 59, in start
    await self.teletaskip_interface.start(host,port,True,60)
  File "/srv/homeassistant/lib/python3.7/site-packages/teletask/io/doip_interface.py", line 28, in start
    await self.interface.connect()
  File "/srv/homeassistant/lib/python3.7/site-packages/teletask/io/client.py", line 114, in connect
    port=self.port)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 959, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 946, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect
    return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

and:
Platform error: light
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 762, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/teletask/light.py", line 4, in <module>
    from homeassistant.components.teletask import (DATA_TELETASK)
ModuleNotFoundError: No module named 'homeassistant.components.teletask'

Any idea what's wrong?

**Comment by jan-bogaerts** [comment]
any word on this?

**Comment by Tiemooowh** [comment]
Hey Jan,

Can you try this one please (this one got the pyTeletask requirement +
embeds the component itself too).
Reason why the custom_component fails is probably because of the lack
fo pyteletask begin installed.

https://github.com/Tiemooowh/core/tree/features/teletask

Br
T
